### ISSUE TITLE
Compressed files wrong format.

### ISSUE THREAD

**Issue by czM1K3** [interclip/interclip#215]
When I want to upload a file with extension .tar.gz the .tar is stripped away and after download, it is not a valid file and I have to rename it back to .tar.gz.
It's really annoying when you want to share the file with someone else that don't know about it.

**Comment by filiptronicek** [comment]
Finally fixed... sorry! 😬 https://github.com/interclip/next/commit/13f6e2747f9dfe099252ba026474c0a8e79e23a6

But as they say... the best things in life take time
