### ISSUE TITLE
Data dump at clip receiving

### ISSUE THREAD

**Issue by tomasdav9** [interclip/interclip#247]
Looks like print_r function at production, just to let you know. :)
![image](https://user-images.githubusercontent.com/68736910/184085439-c05c2f98-d5ca-40e2-909b-a3b69d6bcb13.png)

**Comment by filiptronicek** [comment]
Hey @tomasdav9, thanks for documenting the issue. It looks like I really forgot to remove some "temporary" debugging line. I'll take a look ASAP.

**Comment by filiptronicek** [comment]
@tomasdav9 could you check again? Should be fixed

**Comment by tomasdav9** [comment]
Nice & clear :)
![image](https://user-images.githubusercontent.com/68736910/184093477-773bf89b-8057-4f8e-bd71-c8ff3c007b84.png)

**Comment by filiptronicek** [comment]
Great!
